### ISSUE TITLE
Set Background-Color over full Page

### ISSUE THREAD

**Issue by jkrgr0** [cakebake/markdown-themeable-pdf#35]
Hi, 

I'm currently trying to set the background-color over the full page of a pdf-export.
i try to declare the background-color in css as followed:

``` css
html {
    background-color: #263238;
    /*padding: 20px;*/
}
```

Or

``` css
body {
    background-color: #263238;
}
```

but the result shows, that there is a white border around the content of the page.
![tmp_issue](https://cloud.githubusercontent.com/assets/6506725/13281270/1ffef334-dae3-11e5-8a50-0f86174bbc76.png)

Is it possible to set the "Page-color"?
