### ISSUE TITLE
Appearance of checkboxes

### ISSUE THREAD

**Issue by boborbt** [cakebake/markdown-themeable-pdf#81]
As a personal preference, I don't find the current default styling of checkboxes particularly attractive:

![screen shot 2017-06-08 at 11 56 57](https://user-images.githubusercontent.com/204476/26922929-efdfb956-4c40-11e7-910a-246c2e8e6496.png)

After playing a bit with the stylesheet I ended up with:

![screen shot 2017-06-08 at 11 56 07](https://user-images.githubusercontent.com/204476/26922964-068bee9a-4c41-11e7-9374-1e47d31a80a9.png)

Using the following css:

```css
input[type=checkbox] {
    padding-left:5px;
    padding-right:5px;
    border-radius:2px;

    -webkit-appearance:button;

    border: solid 1px #DDD;

    background-color: #FFF;
    color:#FFF;
    white-space: nowrap;
    overflow:hidden;

    position: relative;
    top: 1px;

    width:11px;
    height:11px;
}

input[type=checkbox]:checked {
    border-radius:2px;
    color: black;
}

input[type=checkbox]:before {
    content: "\2713";
    position:relative;
    top: -1px;
    left: -3px;
}
```

I wonder if the above solution may be of general interest and if you would like to receive a pull request that adds that code to the default style sheet (if you do prefer to add it yourself feel free to use it at your discretion).

I am no designer and better designs certainly are easily achievable. Also, the above code works well with the default styling, but it is likely to break as soon as default size for fonts and other elements are changed.
